ftxxxx-objs                             += ftxxxx_ts.o ftxxxx_ex_fun.o focaltech_ctl.o
obj-$(CONFIG_CC_TOUCHSCREEN_FT5526)   += ftxxxx.o
obj-$(CONFIG_CC_TOUCHSCREEN_FT5626)   += ftxxxx.o
obj-$(CONFIG_CC_TOUCHSCREEN_FT5726)   += ftxxxx.o
