# obj-y      += unicamx.o
# unicamx-objs := unicam.o ad5823.o dw9714.o vm149c.o ad5823_aptina.o bu64243.o

unicam_driver-objs := unicam.o ad5823.o dw9714.o vm149c.o ad5823_aptina.o bu64243.o
obj-$(CONFIG_VIDEO_UNICAM) += unicam_driver.o

obj-$(CONFIG_VIDEO_UNICAM) += soc/

# ccflags-y += -Werror
