ov5648_driver-objs := ov5648.o dw9714.o wv511.o vcm.o
obj-$(CONFIG_VIDEO_OV5648B)     += ov5648_driver.o

obj-$(CONFIG_VIDEO_OV2680)     += ov2680.o
obj-$(CONFIG_VIDEO_OV2680B)     += ov2680b.o
obj-$(CONFIG_VIDEO_GC2155)     += gc2155.o
obj-$(CONFIG_VIDEO_GC0310)     += gc0310.o

#obj-$(CONFIG_VCM_DW9714)     += dw9714.o
