#
# Compass Slaves MPUxxxx
#

obj-$(CONFIG_MPU_SENSORS_AK8963) += inv_mpu_ak8963.o
inv_mpu_ak8963-objs +=	ak8963.o

EXTRA_CFLAGS += -Idrivers/misc/inv_mpu
EXTRA_CFLAGS += -D__C99_DESIGNATED_INITIALIZER
